import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TinyApp</title>)
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />  

      <main className={styles.main}>
        <h1 className={styles.title}>
          Shorten your links today!
        </h1>
      </main>

      <Footer />
    </div>
  )
}
